#intialize the parameters for the model 

AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] #as per VGG16 model from keras application
BATCH_SIZE: 16 #more compute --> more batches
INCLUDE_TOP: False #need pretrained model, instead of training from scratch
EPOCH: 1 #can increase the number of epochs
CLASSES: 2 #disease or non-disease
WEIGHTS: imagenet #image classification is already trained on imagenet
LEARNING_RATE: 0.01
