artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Shabucode/Datasets/raw/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

#assiging paths to all files here, later if you want to change
#any folder location, you can change here, it will automaticallu
#reflect in the code where these files are called.
#Data Ingestion

#update the config.yaml

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5  #add custom layer on top and save as an updated model